read_path: data/John Bunyan___The Works of John Bunyan.txt
search_text:
  |
    "my father was a gipsy and his name was bunyan"
search_text__long:
  |
    "She interrupted me by slowly shaking her forefinger.
      "Young man, trust me. I've lived in the world rather longer than you
      have. All I ask you is to keep your eyes open. You'll see what I mean."
      
      The throb of the motor came through the open window, and Miss Howard
      rose and moved to the door. John's voice sounded outside. With her hand
      on the handle, she turned her head over her shoulder, and beckoned to
      me.
      
      "Above all, Mr. Hastings, watch that devil--her husband!"
      
      There was no time for more. Miss Howard was swallowed up in an eager
      chorus of protests and good-byes. The Inglethorps did not appear.
      
      As the motor drove away, Mrs. Cavendish suddenly detached herself from
      the group, and moved across the drive to the lawn to meet a tall bearded
      man who had been evidently making for the house. The colour rose in her
      cheeks as she held out her hand to him.
      
      "Who is that?" I asked sharply, for instinctively I distrusted the man.
      
      "That's Dr. Bauerstein," said John shortly.
      
      "And who is Dr. Bauerstein?"
      
      "He's staying in the village doing a rest cure, after a bad nervous
      breakdown. He's a London specialist; a very clever man--one of the
      greatest living experts on poisons, I believe."
      
      "And he's a great friend of Mary's," put in Cynthia, the irrepressible.
      
      John Cavendish frowned and changed the subject.
      
      "Come for a stroll, Hastings. This has been a most rotten business. She
      always had a rough tongue, but there is no stauncher friend in England
      than Evelyn Howard."